### ISSUE TITLE
Latest Commit breaks 10 of your production builds - nothing short of a catastrophy 

### ISSUE THREAD

**Issue by nottinhill** [ionic-team/cordova-plugin-wkwebview-engine#182] opened 2017-09-20 23:34 UTC
```
    »         ** BUILD FAILED **
287
    »         The following build commands failed:
288
    »         CompileC /Users/buddybuild/Library/Developer/Xcode/DerivedData/SaveUp-febdjqtkroiqeqcabjrumzqdsxdr/Build/Intermediates/SaveUp.build/Debug-iphonesimulator/SaveUp.build/Objects-normal/x86_64/CDVWKWebViewEngine.o SaveUp/Plugins/cordova-plugin-wkwebview-engine/CDVWKWebViewEngine.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
289
    »         (1 failure)
290
    ✗ Error code 65 for command: xcodebuild with args: -xcconfig,/private/tmp/sandbox/workspace/platforms/ios/cordova/build-debug.xcconfig,-workspace,SaveUp.xcworkspace,-scheme,SaveUp,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/private/tmp/sandbox/workspace/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/private/tmp/sandbox/workspace/platforms/ios/build/sharedpch

```

We have a release tomorrow in 8 hours at a Fortune 500 company and as it looks all systems red due to latest update of wkwebview plugin. Please advice.

**Comment by manucorporat** [comment] 2017-09-21 00:02
Remove platforms/ and plugins/ folder and recreate with cordova again.

**Comment by manucorporat** [comment] 2017-09-21 00:04
It is not a bug related to the code of this plugin: https://stackoverflow.com/questions/34166175/cordova-run-with-ios-error-error-code-65-for-command-xcodebuild-with-args

Closing

**Comment by manucorporat** [comment] 2017-09-21 00:04
Just to make sure, try to update Xcode 9

**Closed by manucorporat** 2017-09-21 00:04 UTC
